### ISSUE TITLE
definitions.json - Missing neutral gender

### ISSUE THREAD

**Issue by lechnerc77** [riskine/ontology#1]
The gender enumeration in the /core/definitions.json is restricted to two genders (male/female). There should be one gender-neutral option available.
Sticking to the CDC standard at least the third option "o - others" should be added.

**Comment by bponleitner** [comment]
Dear @lechnerc77 

thank you for your contribution and sending the first pull request!

We are looking forward to other suggestions for improving the Global Insurance Ontology.
